from pydantic import BaseModel, Field
from enum import Enum
from typing import Optional
from datetime import datetime

# 1. Enums for consistency (No "youtube", "YouTube", "YOUTUBE" mess)
class Platform(str, Enum):
    YOUTUBE = "youtube"
    INSTAGRAM = "instagram"
    EMAIL = "email"

class QueryStatus(str, Enum):
    RECEIVED = "received"
    PROCESSING = "processing"
    ANSWERED = "answered"
    FLAGGED = "flagged"

# 2. The Core Data Payload (The "Message" moving through RabbitMQ)
class StudentQuery(BaseModel):
    id: Optional[str] = None  # Will be generated by MongoDB
    platform: Platform
    sender_id: str  # Username or Email
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    status: QueryStatus = QueryStatus.RECEIVED
    
    # Analysis results (Added by AI Service later)
    sentiment_score: Optional[float] = None
    category: Optional[str] = None
    ai_response: Optional[str] = None
    
    class Config:
        # This allows Pydantic to work with MongoDB's BSON ID
        populate_by_name = True